apiVersion: helmetica.io/v1
kind: InstanceRevision
metadata:
  name: podinfo-release-r4
  namespace: default
  creationTimestamp: "2026-07-08T16:01:29Z"
spec:
  ociUrl: oci://ghcr.io/stefanprodan/charts/podinfo
  version: 6.7.1
  values:
    replicaCount: 4
    ui:
      message: "production"
      color: "#a83279"
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
